/*
 * Copyright [2022] [Tatsuaki Kobayashi]

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */
package io.github.tatsunidas.radiomics.features;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

import ij.ImagePlus;
import ij.measure.Calibration;
import io.github.tatsunidas.radiomics.main.ImagePreprocessing;
import io.github.tatsunidas.radiomics.main.RadiomicsJ;
import io.github.tatsunidas.radiomics.main.Utils;

/**
 * The (cumulative) intensity-volume histogram (IVH) 
 * @author tatsunidas
 *
 */
public class IntensityVolumeHistogramFeatures extends AbstractRadiomicsFeature{
	
	final int label;
	ImagePlus dciImg;//Discretised image was generated by binWidth.
	ImagePlus cciImg;//Continuous calibrated image generated by dciImg.
	Calibration orgCal;
	boolean continuousCalibrated = false;
	
	HashMap<Double, double[]> dciIVHisto;
	HashMap<Double, double[]> cciIVHisto;
	
	public IntensityVolumeHistogramFeatures(ImagePlus img, ImagePlus mask, Map<String,Object> settings) {
		super(img, mask, settings);
		Object labelValue = settings.get(RadiomicsFeature.LABEL);
		if (labelValue == null) {
			throw new IllegalArgumentException("'label' is missing in settings.");
		}
		if (!(labelValue instanceof Integer)) {
			throw new IllegalArgumentException("'label' must be an Integer.");
		}
		this.label = (Integer) labelValue;
		buildup(settings);
	}

	/**
	 * 
	 * if continuousCalibrated is false, use original as discretised images (same as no descretising).
	 * 
	 * @param img
	 * @param mask
	 * @param label
	 * @param nBins
	 * @param mode: 0:No discretize (default), 1 binWidth, 2 binCount
	 * @throws Exception
	 */
	public IntensityVolumeHistogramFeatures(ImagePlus img, ImagePlus mask, int label, int mode) throws Exception {
		super(img, mask, null);
		this.label = label;
		/*
		 * create mask
		 */
		if(mask == null) {
			this.mask = ImagePreprocessing.createMask(img.getWidth(), img.getHeight(), img.getNSlices(), null, this.label,img.getCalibration().pixelWidth, img.getCalibration().pixelHeight,img.getCalibration().pixelDepth);
		}
		this.img = img;
		orgCal = this.img.getCalibration().copy();
		
		/*
		 * !IVH mode 0:No discretise (default)
		 * !IVH mode 1:Use discretise with binWidth
		 * !IVH mode 2:Use discretise with binCount
		 * !IVH mode other value : set back to defalut
		 */
		if(mode ==1) {
			this.continuousCalibrated = true;
			dciImg = Utils.discreteByBinWidth(this.img, this.mask, this.label, RadiomicsJ.IVH_binWidth);
			cciImg = Utils.convertBinCenter2Intensity(this.img, dciImg, this.mask, this.label, RadiomicsJ.IVH_binWidth);
			if(dciImg == null || cciImg == null) {
				throw new IllegalArgumentException("IntensityVolumeHistogramFeature calculation was failed. Please check image data.");
			}
			calculateIVHistogram4CCI(false);//init cciIVHisto;
		}else if(mode ==2) {
			this.continuousCalibrated = false;
			dciImg = Utils.discrete(this.img, this.mask, this.label, RadiomicsJ.IVH_binCount);
			if(dciImg == null) {
				throw new IllegalArgumentException("IntensityVolumeHistogramFeature calculation was failed. Please check image data.");
			}
			calculateIVHistogram4DCI(RadiomicsJ.debug);//init dciIVHisto;
		}else {
			this.continuousCalibrated = false;
			dciImg = this.img;
			calculateIVHistogram4DCI(RadiomicsJ.debug);//init dciIVHisto;
		}
		settings.put(RadiomicsFeature.IMAGE, this.img);
		settings.put(RadiomicsFeature.MASK, this.mask);
		settings.put(RadiomicsFeature.LABEL, this.label);
		settings.put(RadiomicsFeature.IVH_MODE, mode);
		settings.put(RadiomicsFeature.BinCount_IVH, RadiomicsJ.IVH_binCount);
		settings.put(RadiomicsFeature.BinWidth_IVH, RadiomicsJ.IVH_binWidth);
		
	}
	
	public void buildup(Map<String,Object> settings) {
		if(mask == null) {
			mask = ImagePreprocessing.createMask(img.getWidth(), img.getHeight(), img.getNSlices(), null, this.label,img.getCalibration().pixelWidth, img.getCalibration().pixelHeight,img.getCalibration().pixelDepth);
		}
		orgCal = this.img.getCalibration().copy();
		
		Object modeValue = settings.get(RadiomicsFeature.IVH_MODE);
		if (modeValue == null) {
			throw new IllegalArgumentException("'IVH_MODE' is missing in settings.");
		}
		if (!(modeValue instanceof Integer)) {
			throw new IllegalArgumentException("'IVH_MODE' must be an Integer.");
		}
		int mode = (Integer)modeValue;
		if(mode ==1) {
			this.continuousCalibrated = true;
			try {
				dciImg = Utils.discreteByBinWidth(this.img, this.mask, this.label, RadiomicsJ.IVH_binWidth);
			} catch (Exception e) {
				e.printStackTrace();
			}
			cciImg = Utils.convertBinCenter2Intensity(this.img, dciImg, this.mask, this.label, RadiomicsJ.IVH_binWidth);
			if(dciImg == null || cciImg == null) {
				throw new IllegalArgumentException("IntensityVolumeHistogramFeature calculation was failed. Please check image data.");
			}
			calculateIVHistogram4CCI(false);//init cciIVHisto;
		}else if(mode ==2) {
			this.continuousCalibrated = false;
			try {
				dciImg = Utils.discrete(this.img, this.mask, this.label, RadiomicsJ.IVH_binCount);
			} catch (Exception e) {
				e.printStackTrace();
			}
			if(dciImg == null) {
				throw new IllegalArgumentException("IntensityVolumeHistogramFeature calculation was failed. Please check image data.");
			}
			calculateIVHistogram4DCI(RadiomicsJ.debug);//init dciIVHisto;
		}else {
			this.continuousCalibrated = false;
			dciImg = this.img;
			calculateIVHistogram4DCI(RadiomicsJ.debug);//init dciIVHisto;
		}
	}
	
	public Double calculate(String id) {
		
		String name = IntensityVolumeHistogramFeatureType.findType(id);
		if (name.equals(IntensityVolumeHistogramFeatureType.VolumeAtIntensityFraction10.name())) {
			return getVolumeAtIntensityFraction(10, continuousCalibrated);
		}else if (name.equals(IntensityVolumeHistogramFeatureType.VolumeAtIntensityFraction90.name())) {
			return getVolumeAtIntensityFraction(90, continuousCalibrated);
		}else if (name.equals(IntensityVolumeHistogramFeatureType.IntensityAtVolumeFraction10.name())) {
			return getIntensityAtVolumeFraction(10, continuousCalibrated);
		}else if (name.equals(IntensityVolumeHistogramFeatureType.IntensityAtVolumeFraction90.name())) {
			return getIntensityAtVolumeFraction(90, continuousCalibrated);
		}else if (name.equals(IntensityVolumeHistogramFeatureType.VolumeFractionDifferenceBetweenIntensityFractions.name())) {
			return getVolumeFractionDifferenceBetweenIntensityFractions();
		}else if (name.equals(IntensityVolumeHistogramFeatureType.IntensityFractionDifferenceBetweenVolumeFractions.name())) {
			return getIntensityFractionDifferenceBetweenVolumeFractions();
		}else if (name.equals(IntensityVolumeHistogramFeatureType.AreaUnderTheIVHCurve.name())) {
			return getAreaUnderTheIVHCurve();
		}
		return null;
	}
	
	/**
     * Optimized IVHistogram for Discretised calibrated image intensities (DCI)
     * 計算量: O(N) でカウント + O(B log B) でソート (TreeMap)
     */
	private HashMap<Double, double[]> calculateIVHistogram4DCI(boolean verbose) {
		HashMap<Double, double[]> iv_histo = new HashMap<>();

		// 1. 全ボクセルを取得
		double[] discretisedVoxels = Utils.getVoxels(dciImg, mask, label);
		int totalVoxels = discretisedVoxels.length;
		if (totalVoxels == 0)
			return iv_histo;

		// 2. 最小・最大値の決定 (Gamma計算用)
		double min, max;
		if (RadiomicsJ.rangeMin != null && RadiomicsJ.rangeMax != null) {
			min = RadiomicsJ.rangeMin;
			max = RadiomicsJ.rangeMax;
		} else {
			// StatUtilsを使うと2回走査になるため、ループ内で求めるか、事前に求める
			// ここでは元のロジックに合わせてUtils.getVoxels(img...)から取るか、
			// 単純化のため discretisedVoxels から計算します（離散化済み画像の範囲）
			min = Double.MAX_VALUE;
			max = -Double.MAX_VALUE;
			for (double v : discretisedVoxels) {
				if (v < min)
					min = v;
				if (v > max)
					max = v;
			}
		}

		// Range check to avoid division by zero
		double range = (max - min);
		if (range == 0)
			range = 1.0;

		// 3. 頻度カウント (Frequency Counting) - O(N)
		// TreeMapを使うことでKey(強度)が自然順序(昇順)で保持されます
		TreeMap<Double, Integer> frequencyMap = new TreeMap<>();
		for (double v : discretisedVoxels) {
			frequencyMap.put(v, frequencyMap.getOrDefault(v, 0) + 1);
		}

		// 4. 累積ヒストグラムの作成 - O(B)
		// IBSI定義: nu(x) は "強度 x 以上のボクセル数の割合"
		// TreeMapは昇順なので、降順イテレータ(descendingMap)を使うと累積計算が楽です

		long cumulativeCount = 0; // x以上の累積カウント

		// 大きい強度から順に処理
		for (Map.Entry<Double, Integer> entry : frequencyMap.descendingMap().entrySet()) {
			double intensity = entry.getKey();
			int count = entry.getValue();

			cumulativeCount += count;

			double nyu = (double) cumulativeCount / totalVoxels; // 累積体積分率
			double gamma = (intensity - min) / range; // 強度分率

			// Gammaが範囲外(0-1)になる場合のクリッピング（浮動小数点誤差対策）
			if (gamma < 0)
				gamma = 0;
			if (gamma > 1)
				gamma = 1;

			iv_histo.put(intensity+1/*1-based*/, new double[] { nyu, gamma });
		}

		this.dciIVHisto = iv_histo;
		return this.dciIVHisto;
	}
	
	
	/**
	 * Optimized IVHistogram for Continuous calibrated image intensities (CCI) 計算量:
	 * O(N) + O(B log B)
	 */
	private HashMap<Double, double[]> calculateIVHistogram4CCI(boolean verbose) {
		HashMap<Double, double[]> iv_histo = new HashMap<>();

		// 1. 全ボクセルを取得 (CCI画像から直接取得)
		double[] discretisedVoxels_cci = Utils.getVoxels(cciImg, mask, label);
		int totalVoxels = discretisedVoxels_cci.length;
		if (totalVoxels == 0)
			return iv_histo;

		// 2. 最小・最大値の決定
		double min, max;
		if (RadiomicsJ.rangeMin != null && RadiomicsJ.rangeMax != null) {
			min = RadiomicsJ.rangeMin;
			max = RadiomicsJ.rangeMax;
		} else {
			min = Double.MAX_VALUE;
			max = -Double.MAX_VALUE;
			for (double v : discretisedVoxels_cci) {
				if (v < min)
					min = v;
				if (v > max)
					max = v;
			}
		}

		double range = (max - min);
		if (range == 0)
			range = 1.0;

		// 3. 頻度カウント - O(N)
		// CCIの場合、値は離散化された連続値（ビン中心）になっています
		TreeMap<Double, Integer> frequencyMap = new TreeMap<>();
		for (double v : discretisedVoxels_cci) {
			frequencyMap.put(v, frequencyMap.getOrDefault(v, 0) + 1);
		}

		// 4. 累積ヒストグラムの作成 - O(B)
		long cumulativeCount = 0;

		// 大きい強度から順に処理 (nuは "以上" の割合なので上から足す)
		for (Map.Entry<Double, Integer> entry : frequencyMap.descendingMap().entrySet()) {
			double intensity = entry.getKey();
			int count = entry.getValue();

			cumulativeCount += count;

			double nyu = (double) cumulativeCount / totalVoxels;
			double gamma = (intensity - min) / range;

			if (gamma < 0)
				gamma = 0;
			if (gamma > 1)
				gamma = 1;

			iv_histo.put(intensity, new double[] { nyu, gamma });
		}

		this.cciIVHisto = iv_histo;
		return this.cciIVHisto;
	}
	
	private Double getVolumeAtIntensityFraction(int p_th, boolean continuousCalibrated) {
		HashMap<Double, double[]> histo = continuousCalibrated ? cciIVHisto : dciIVHisto;
		ArrayList<Double> al = new ArrayList<>(histo.keySet());
		Collections.sort(al);// sort for discretized order.
		for (int i = 0; i < histo.size(); i++) {
			double gamma = histo.get(al.get(i))[1];
			if (gamma >= p_th / 100d) {
				return histo.get(al.get(i))[0];// nyu
			}
		}
		return null;
	}
	
	private Double getIntensityAtVolumeFraction(int p_th, boolean continuousCalibrated) {
		HashMap<Double, double[]> histo = continuousCalibrated ? cciIVHisto : dciIVHisto;
		ArrayList<Double> al = new ArrayList<>(histo.keySet());
		Collections.sort(al, Collections.reverseOrder());
		for (int i = 0; i < al.size(); i++) {
			double val = al.get(i);
			double nyu = histo.get(val)[0];
			if (nyu >= p_th / 100d) {
				return val;
			}
		}
		return null;
	}
	
	
	private Double getVolumeFractionDifferenceBetweenIntensityFractions() {
		Double v10 = getVolumeAtIntensityFraction(10, this.continuousCalibrated);
		Double v90 = getVolumeAtIntensityFraction(90, this.continuousCalibrated);
		if(v10 == null || v90 == null) {
			return null;
		}
		return v10-v90;
	}
	
	private Double getIntensityFractionDifferenceBetweenVolumeFractions() {
		Double v10 = getIntensityAtVolumeFraction(10, this.continuousCalibrated);
		Double v90 = getIntensityAtVolumeFraction(90, this.continuousCalibrated);
		if (v10 == null || v90 == null) {
			return null;
		}
		return v10 - v90;
	}
	
	/**
	 * The area under the IVH curve can be approximated by calculating the Riemann
	 * sum using the trapezoidal rule. Note that if there is only one discretised
	 * intensity in the ROI, we define the area under the IVH curve F.ivh.auc = 0
	 * https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2701316/
	 */
	private Double getAreaUnderTheIVHCurve() {

		HashMap<Double, double[]> histo = continuousCalibrated ? cciIVHisto : dciIVHisto;
		ArrayList<Double> al = new ArrayList<>(histo.keySet());
		Collections.sort(al);

		double sum_auc = 0d;
		for (int i = 0; i < al.size() - 1; i++) {
			double val1 = al.get(i);
			double val2 = al.get(i + 1);

			// mapの配列 [0]がnu(体積分率), [1]がgamma(強度分率)
			double nu1 = histo.get(val1)[0];
			double nu2 = histo.get(val2)[0];
			double gamma1 = histo.get(val1)[1];
			double gamma2 = histo.get(val2)[1];

			// 横軸はGammaの差分を使う
			double deltaGamma = gamma2 - gamma1;

			// 台形公式
			sum_auc += (deltaGamma * (nu1 + nu2)) / 2.0;
		}
		return sum_auc; // sizeで割らない
		
//		if (!continuousCalibrated) {
//			ArrayList<Double> al = new ArrayList<>(dciIVHisto.keySet());
//			Collections.sort(al);
//			int size = al.size();
//			double sum_nu = 0d;
//			for (int i = 0; i < size; i++) {
//				if (i + 1 == size) {
//					break;
//				}
//				double d1 = al.get(i);
//				double d2 = al.get(i + 1);
//				double nu1 = dciIVHisto.get(al.get(i))[0];// nu:fractional volume
//				double nu2 = dciIVHisto.get(al.get(i + 1))[0];
//				double delta = (d2 - d1);
//				sum_nu += delta/2d * (nu1 + nu2);
//			}
//			return sum_nu / size;
//		} else {
//			ArrayList<Double> al = new ArrayList<>(cciIVHisto.keySet());
//			Collections.sort(al);
//			int size = al.size();
//			double sum_nu = 0d;
//			for (int i = 0; i < size; i++) {
//				if (i + 1 == size) {
//					break;
//				}
//				double d1 = al.get(i);
//				double d2 = al.get(i + 1);
//				double nu1 = cciIVHisto.get(al.get(i))[0];// nu:fractional volume
//				double nu2 = cciIVHisto.get(al.get(i + 1))[0];
//				double delta = (d2 - d1);
//				sum_nu += delta/2d * (nu1 + nu2);
//			}
//			return sum_nu / size;
//		}
	}
	
	public String toString() {
		if(!continuousCalibrated) {
			ArrayList<Double> al = new ArrayList<>(dciIVHisto.keySet());
			Collections.sort(al);
			int size = al.size();
			System.out.println("===  IVH result (nBins)  ===");
			for(int i=0;i<size;i++) {
				double discVal = al.get(i);
				double nu = dciIVHisto.get(discVal)[0];
				double gamma = dciIVHisto.get(discVal)[1];
				System.out.println("discretised value:"+discVal+", gamma:"+gamma+", nu:"+nu);
			}
		}else {
			ArrayList<Double> al = new ArrayList<>(cciIVHisto.keySet());
			Collections.sort(al);
			int size = al.size();
			System.out.println("===  IVH result (continus, binWidth)  ===");
			for(int i=0;i<size;i++) {
				double discVal = al.get(i);
				double nu = cciIVHisto.get(discVal)[0];
				double gamma = cciIVHisto.get(discVal)[1];
				System.out.println("discretised value:"+discVal+", gamma:"+gamma+", nu:"+nu);
			}
		}
		System.out.println("=== IVH result end ===");
		return null;
	}

	@Override
	public Set<String> getAvailableFeatures() {
		Set<String> names = new HashSet<String>();
		for(IntensityVolumeHistogramFeatureType t : IntensityVolumeHistogramFeatureType.values()) {
			names.add(t.name());
		}
		return names;
	}

	@Override
	public String getFeatureFamilyName() {
		return "IntensityVolumeHistogram";
	}

	@Override
	public Map<String, Object> getSettings() {
		return settings;
	}

}
